### ISSUE TITLE
Decorator annotation value is not used?

### ISSUE THREAD

**Issue by apilets** [AgataPochebut/AudioStreamingService#12]
https://github.com/AgataPochebut/AudioStreamingService/blob/5f54c4c0caae216d18da3fd34957d3a4fecb70e5/song-service/src/main/java/com/epam/songservice/SongServiceApplication.java#L77

Please fix. No need to always wrap implementations with ResourceIORetryDecorator and ResourceDBDecorator. Add decoration when it is specified in the annotation. 

Think about how to add multiple decorations:
@Decorate(decorations = {ResourceIORetryDecorator.class, ResourceDBDecorator.class})

**Comment by AhataPachabut** [comment]
Как я понимаю в BeanPostProcessor ловлю бины с аннотацией @Decorate.
Для бина из аннотации получаю значение decorations  - массив классов-декораторов {ResourceIORetryDecorator.class, ResourceDBDecorator.class}. 
Прохожусь циклом по этим декораторам и создаю экземпляр класса и передаю в параметры бин.
Если эта логика верна, то:
1. у каждой реализации должна быть прописана аннотация со списком декораторов? а реализации у меня 2 и список одинаков. я не вижу смысла.
2. нужно универсальным механизмом создавать экземпляры любого класса декоратора. Каждый декоратор это не бин т.е. не могу его сделать @Service и @Autowired там не работает, а значит все поля передаются через конструктор. Везде разные поля. Не понимаю как через универсальное создание это сделать. Ну, только если везде передавать весь контекст. А это нормально?
И получается при добавлении декоратора сейчас нужно только в постпроцессор дописать, а иначе придется в каждой реализации интерфейса дополнять список декораторов.

**Comment by apilets** [comment]
1. Этот список может быть другим в будущем. Идея с декорациями состоит в том, что мы можем гибко менять поведение реализации сервиса
2. Можно сделать либо декораторы бинами, но тогда нужно подумать про скоуп. Либо инжектать все зависимости в фэктори и передавать их в конструктор

**Comment by AhataPachabut** [comment]
повесила аннотацию на интерфейс
сделала декораторы через фэктори
